version: "3"
services:
  app:
    image: mhart/alpine-node:8
    ports:
      - "8080:8080"
    command: "npm start"  
    volumes:
      - ./:/app
    working_dir: /app    
  mongo:
    image: mongo     